version: '3.7'

x-backend-service: &x-backend-service
  image: briler/django-ocpp-manager:latest
  env_file:
    - .env
  restart: unless-stopped

services:
  ocpp_consumer:
    <<: *x-backend-service
    command: python manage.py run_ocpp_consumer
    restart: always

  migrate:
    <<: *x-backend-service
    command: python manage.py migrate --noinput
    restart: "no"

  backend:
    <<: *x-backend-service
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    command: [ "gunicorn", "-c", "/app/app/gunicorn.py", "app.wsgi" ]

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - static_volume:/static
      - ./nginx/static/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 django-ocpp-manager

  celery:
    <<: *x-backend-service
    volumes:
      - ./runtime:/app/runtime
    command: celery -A app worker --loglevel=debug


volumes:
  static_volume:
