version: '3.7'

x-backend-service: &x-backend-service
  image: briler/django-ocpp-manager:latest
  env_file:
    - .env
  restart: unless-stopped

services:
  migrate:
    <<: *x-backend-service
    command: python manage.py migrate --noinput
    restart: "no"

  backend:
    <<: *x-backend-service
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    command: [ "gunicorn", "-c", "/app/app/gunicorn.py", "app.wsgi" ]
  #
  #  manager:
  #    container_name: csms-manager
  #    build:
  #      context: ..
  #      dockerfile: Dockerfile
  #    volumes:
  #      - .:/usr/src/csms
  #    ports:
  #      - "8001:${HTTP_SERVER_PORT}"
  #    env_file:
  #      - .env
  #    networks:
  #      - app-network
  #    restart: always
  #    command: >
  #      sh -c "cd /usr/src/csms && alembic upgrade head &&
  #             uvicorn manager.main:app --host 0.0.0.0 --port 8001 --reload"
  #    depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      db:
  #        condition: service_healthy
  #    healthcheck:
  #      test: "exit 0"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - static_volume:/static
      - ./nginx/static/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 django-ocpp-manager


volumes:
  static_volume:
