version: '3.7'

x-backend-service: &x-backend-service
  image: briler/django-ocpp-manager:latest
  env_file:
    - .env
  restart: unless-stopped

services:
  ocpp_consumer:
    <<: *x-backend-service
    command: python manage.py run_ocpp_consumer
    restart: always

  migrate:
    <<: *x-backend-service
    command: python manage.py migrate --noinput
    restart: "no"

  backend:
    <<: *x-backend-service
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    command: [ "gunicorn", "-c", "/app/app/gunicorn.py", "app.wsgi" ]

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/static/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

  celery:
    <<: *x-backend-service
    volumes:
      - runtime_volume:/app/runtime
    command: celery -A app worker --loglevel=debug
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings

volumes:
  static_volume:
  runtime_volume:
