# Generated by Django 5.0.1 on 2024-02-01 14:22

import django.db.models.deletion
import manager.defaults
import ocpp.v16.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=48, unique=True)),
                ("city", models.CharField(max_length=48)),
                ("address1", models.CharField(max_length=256)),
                ("address2", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="ChargePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge_point_id", models.CharField(max_length=256, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                ocpp.v16.enums.ChargePointStatus["available"],
                                "Available",
                            ),
                            (
                                ocpp.v16.enums.ChargePointStatus["preparing"],
                                "Preparing",
                            ),
                            (ocpp.v16.enums.ChargePointStatus["charging"], "Charging"),
                            (
                                ocpp.v16.enums.ChargePointStatus["suspended_evse"],
                                "SuspendedEVSE",
                            ),
                            (
                                ocpp.v16.enums.ChargePointStatus["suspended_ev"],
                                "SuspendedEV",
                            ),
                            (
                                ocpp.v16.enums.ChargePointStatus["finishing"],
                                "Finishing",
                            ),
                            (ocpp.v16.enums.ChargePointStatus["reserved"], "Reserved"),
                            (
                                ocpp.v16.enums.ChargePointStatus["unavailable"],
                                "Unavailable",
                            ),
                            (ocpp.v16.enums.ChargePointStatus["faulted"], "Faulted"),
                        ],
                        default=ocpp.v16.enums.ChargePointStatus["unavailable"],
                        max_length=50,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=48, null=True, unique=True),
                ),
                ("model", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("connectors", models.JSONField(default=dict, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_points",
                        to="manager.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charge Point",
                "verbose_name_plural": "Charge Points",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag_id",
                    models.CharField(
                        default=manager.defaults.tagid_generator, max_length=20
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=48, null=True)),
                ("vehicle", models.CharField(blank=True, max_length=256, null=True)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("meter_start", models.IntegerField()),
                ("meter_stop", models.IntegerField(blank=True, null=True)),
                (
                    "meter_value_raw",
                    models.JSONField(
                        blank=True, default=dict, editable=False, null=True
                    ),
                ),
                ("connector_id", models.IntegerField(default=1)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "charge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="manager.chargepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
