# Generated by Django 5.0.1 on 2024-01-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chargepoint",
            options={
                "verbose_name": "Charge Point",
                "verbose_name_plural": "Charge Points",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.RenameField(
            model_name="chargepoint",
            old_name="password",
            new_name="password_hash",
        ),
        migrations.AlterField(
            model_name="chargepoint",
            name="connectors",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="chargepoint",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_points",
                to="manager.location",
            ),
        ),
    ]
