# Generated by Django 5.0.1 on 2024-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
