# Generated by Django 5.0.1 on 2024-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="meter_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
