# Generated by Django 5.0.1 on 2024-03-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_chargepoint_last_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=80,
                        verbose_name="Action",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, editable=False, null=True
                    ),
                ),
                (
                    "charge_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="manager.chargepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
            },
        ),
    ]
