# Generated by Django 5.0.1 on 2024-02-01 15:13

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_alter_transaction_meter_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    (manager.models.TransactionStatus["initialized"], "initialized"),
                    (manager.models.TransactionStatus["started"], "started"),
                    (manager.models.TransactionStatus["stopped"], "stopped"),
                ],
                default=manager.models.TransactionStatus["initialized"],
                max_length=50,
            ),
        ),
    ]
