# Generated by Django 5.0.1 on 2024-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=80,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
