# Generated by Django 5.0.1 on 2024-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_alter_chargepoint_password_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargepoint",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
