# Generated by Django 5.0.1 on 2024-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_alter_transaction_charge_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="code",
            field=models.CharField(default="1", max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
