# Generated by Django 5.0.1 on 2024-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0006_chargepoint_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargepoint",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="chargepoint",
            name="model",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="chargepoint",
            name="serial_number",
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
    ]
