# Generated by Django 5.0.1 on 2024-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_alter_chargepoint_manufacturer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chargepoint",
            old_name="code",
            new_name="charge_point_id",
        ),
    ]
