# Generated by Django 5.0.1 on 2024-01-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_rename_code_chargepoint_charge_point_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="meter_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="meter_value_raw",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
