# Generated by Django 5.0.1 on 2024-01-28 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0009_transaction_meter_value_transaction_meter_value_raw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="meter_value",
        ),
    ]
